### ISSUE TITLE
Disable update notification in web UI

### ISSUE THREAD

**Issue by xginn8** [balena-io-examples/balena-netdata#6]
This notification is counterproductive as a sidecar

**Comment by saintaardvark** [comment]
I've had a look through the netdata code (both [netdata/netdata](https://github.com/netdata/netdata) and [netdata/dashboard](https://github.com/netdata/dashboard)), and it doesn't look like there's an immediately obvious way to do this: there isn't a config option to turn off the update-now/sign-in options.  There are 714 issues currently open on their main repo, so I don't think a request to turn this off is going to get a lot of attention real soon. :grin:

Making a custom dashboard would seem to be a good way to accomplish what we want.  If it needs to be a direct copy of the default dashboard, that will be a little tricky: the default index page is configured using React, in what seems to be a different way from the usual method they have for making custom dashboards.  [This is where the charts are defined](https://github.com/netdata/dashboard/blob/master/src/dashboard_info.js#L687); copying the particular data sources will be pretty easy, but getting the look of the dashboard right may mean examining the default dashboard and looking for the individual chart elements (`<div data-netdata="system.cpu">`).

**Comment by saintaardvark** [comment]
Further digging:

- [An issue filed upstream](https://github.com/netdata/netdata/issues/9362) about all this pointed me at [this method for disabling Agent-Cloud](https://learn.netdata.cloud/docs/agent/aclk#disable-the-aclk), which I had managed to miss.  This disables the Netdata Cloud login prompts, though it doesn't remove all their UI elements.  Before disabling Agent-Cloud:

![Screenshot from 2020-06-23 15-48-37](https://user-images.githubusercontent.com/1486793/85474766-f6800500-b569-11ea-81ad-6cc2deaf8ce9.png)

And after:

![Screenshot from 2020-06-23 15-49-02](https://user-images.githubusercontent.com/1486793/85474790-ff70d680-b569-11ea-8dcf-abd44d438ed3.png)


- I've disabled Agent-Cloud in the `netdata-smol` branch mentioned in #7.  The effect isn't has noticeable in the packaged version of Netdata, as the web UI is a bit different; the web UI now mentions "nodes", and it doesn't seem to go away if you disable Agent-Cloud:

![Screenshot from 2020-06-23 15-56-33](https://user-images.githubusercontent.com/1486793/85474917-2929fd80-b56a-11ea-8d74-0d574a0a30d6.png)

- The dashboard repo has a `node-view` target (`npm run start:node-view`) which is just about exactly what we want: the top and left-hand side bars are gone, leaving just the default dashboard.  However, it's hardcoded to point at localhost ([1](https://github.com/netdata/dashboard/blob/master/src/node-view-app.tsx#L56), [2](https://github.com/netdata/dashboard/blob/master/src/node-view-app.tsx#L73), [3](https://github.com/netdata/dashboard/blob/master/src/domains/dashboard/components/node-view/node-view.tsx#L99)), and I'm not nearly expert at Typescript/React enough to know how to remove that.  I've asked [upstream](https://github.com/netdata/netdata/issues/9362) if there's a way to do this.

**Comment by saintaardvark** [comment]
Upstream let us know that they have no plans to disable the "updates available" notice.
